include:
  - template: Jobs/Secret-Detection.latest.gitlab-ci.yml
  - template: Jobs/Dependency-Scanning.latest.gitlab-ci.yml
  - template: Jobs/SAST.latest.gitlab-ci.yml
  - template: Code-Quality.gitlab-ci.yml

build:
  image: node:latest
  stage: build
  before_script:
    - npm install
  script:
    - npm exec tsc
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

test:unit:
  image: node:latest
  stage: test
  before_script:
    - npm i
  script:
    - npm t -- --passWithNoTests
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

test:publish:
  image: node:latest
  stage: test
  before_script:
    - npm install
  script:
    - npm publish --dry-run
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
