const path = require('path');
const fs = require('fs');

export class Scopes {
    root = path.join(process.cwd(), 'node_modules', 'luucy-types');
    scopes = path.join(this.root, 'scopes');
    definitions = path.join(this.root, 'definitions.d.ts');
    packageJson = path.join(process.cwd(), 'package.json');

    add(name: string) {
        if (!this.list().includes(name)) {
            throw new Error(`Scope '${name}' not found. Use 'luucy scope list' to view all available scopes. You may need to update luucy ('luucy upgrade')`);
        }

        const packageConfiguration = JSON.parse(fs.readFileSync(this.packageJson).toString());
        
        if (packageConfiguration.scopes) {
            if (packageConfiguration.scopes.includes(name)) {
                return false;
            }

            packageConfiguration.scopes.push(name);
        } else {
            packageConfiguration.scopes = [name];
        }

        packageConfiguration.scopes = packageConfiguration.scopes.sort((a, b) => a > b);

        fs.writeFileSync(this.packageJson, JSON.stringify(packageConfiguration, null, '\t'));

        this.build();

        return true;
    }

    list() {
        return fs.readdirSync(this.scopes) as string[];
    }

    info(name: string) {
        for (let scope of this.list()) {
            if (scope == name) {
                return JSON.parse(fs.readFileSync(path.join(this.scopes, name, 'scope.json')).toString());
            }
        }
    }

    build() {
        const packageConfiguration = JSON.parse(fs.readFileSync(this.packageJson).toString());
        const available = this.list();

        const declarations = [];

        for (let scope of packageConfiguration.scopes || []) {
            if (!available.includes(scope)) {
                throw new Error(`Scope '${name}' not found. You may need to update luucy ('luucy upgrade')`);
            }

            declarations.push(`/// <reference path="scopes/${scope}/index.d.ts" />`);
        }

        fs.writeFileSync(this.definitions, [
            '// enabled declarations, generated by luucy cli',
            '// autogenerated. changes will be overwritten',
            '',
            '/// <reference no-default-lib="true"/>',
            '/// <reference path="globals/index.d.ts" />',
            '',
            ...declarations
        ].join('\n'));
    }
}