import { Constants } from './constants';

const path = require('path');
const fs = require('fs');
const readline = require('readline-sync');

export class Scopes {
  packageConfiguration: { scopes: string[] };

  available: string[];

  cwd: string;

  constructor(packageConfiguration?: { scopes: string[] }, available?: string[], cwd?: string) {
    this.cwd = cwd || '';
    this.packageConfiguration = packageConfiguration || JSON.parse(fs.readFileSync(path.join(this.cwd, Constants.packageFile)).toString());
    this.available = available || this.list();
  }

  add(name: string) {
    if (!this.list().includes(name)) {
      throw new Error(
        `Scope '${name}' not found. Use 'luucy scope list' to view all available scopes. You may need to update luucy ('luucy upgrade')`
      );
    }

    this.addScope(this.packageConfiguration, name);

    // this.packageConfiguration.scopes = this.packageConfiguration.scopes.sort((a: string, b: string) => a > b);

    fs.writeFileSync(path.join(this.cwd, Constants.packageFile), JSON.stringify(this.packageConfiguration, null, '\t'));

    this.build();

    process.stdout.write(`\nscope '${name}' added successfuly\n\n`);

    return true;
  }

  private addScope(packageConfiguration, name: string) {
    const info = this.info(name);

    if (info.permission) {
      process.stdout.write(`${name}: \x1b[3;33m${info.permission}\x1b[0m\n`);

      if (!readline.keyInYN('Do you really want to add this scope?')) {
        process.exit(2);
      }
    }

    for (const dependency of info.dependencies || []) {
      process.stdout.write(`\x1b[2m→ installing dependency '${dependency}' of '${name}'\x1b[0m\n`);

      this.addScope(packageConfiguration, dependency);
    }

    if (packageConfiguration.scopes) {
      if (packageConfiguration.scopes.includes(name)) {
        return false;
      }

      packageConfiguration.scopes.push(name);
    } else {
      packageConfiguration.scopes = [name];
    }
  }

  list() {
    return this.available || (fs.readdirSync(Constants.scopes) as string[]);
  }

  info(name: string) {
    for (const scope of this.list()) {
      if (scope == name) {
        return JSON.parse(fs.readFileSync(path.join(this.cwd, Constants.scopes, name, 'scope.json')).toString());
      }
    }
  }

  build() {
    const declarations = [];

    for (const scope of this.packageConfiguration.scopes || []) {
      if (!this.available.includes(scope)) {
        throw new Error(`Scope '${scope}' not found. You may need to update luucy ('luucy upgrade')`);
      }

      declarations.push(`/// <reference path="${path.join('..', Constants.scopes, scope, 'index.d.ts')}" />`);
    }

    if (!fs.existsSync(path.join(this.cwd, Constants.managed))) {
      fs.mkdirSync(path.join(this.cwd, Constants.managed));
    }

    fs.writeFileSync(
      path.join(this.cwd, Constants.managedTypes),
      [
        '// enabled declarations, generated by luucy cli',
        '// autogenerated. changes will be overwritten',
        '',
        '/// <reference no-default-lib="true"/>',
        `/// <reference path="${['..', ...Constants.typesRoot, 'globals', 'index.d.ts'].join('/')}" />`,
        '',
        ...declarations
      ].join('\n')
    );
  }
}
